Change annotations for columns in TournamentRegistration class
Annotation @MapsId has been changed to @JoinColumn

@MapsId annotation produced column names like:
roomType_id
stayPeriod_id
weightAgeCategory_id

but Hibernate was looking for columns named like:
room_type_id
stay_period_id
weight_age_category_id

producing error like:
java.sql.SQLSyntaxErrorException: Unknown column '' in 'field list'

Also a @JsonManagedReference has been added to tournamentRegistrarions
in TournamentEvent class.